### PR TITLE
Have a local build script for win32

### LINKED ISSUE #7: Have a local build script for win32
I would like to build Sikuli for win32 from the command line using a script that's included in the root of the repository. I see a `build-win32.txt` file and I started turning it into a batch script. But, I realized that your [Hudson server](http://sikuli.org/hudson/job/Sikuli-Script-Windows/159/console) must have a script or something on it for this already. Can you pull it out of there and check it in?

### PR DESCRIPTION
**Pull request by AnthonyMastrean**
Ok, straightened out my branch issue. Here's a changeset right on develop. Should close #7. I'll play with prerequisite install/configurations and if I find anything interesting, I can submit some docs (wiki? readme? build-win32.txt? any recommendations?)

### CODE REVIEW

**Comment by RaiMan** [comment]
Any chance to get a win64 build too? When I (successfully) tried this a year ago, I had some troubles with the prereqs in 64Bit and with the .net stuff (sorry I am neither a development nor a Windows expert).

--- Where to put information?
I think we should start a page in the Wiki "How to build your own Sikuli" or something like that.

**Comment by AnthonyMastrean** [comment]
If it builds/runs on win32 (or, more accurately, x86), is there any reason to make an x64 version? I'm running Windows x64, but I can _build_ the x86 version just fine. Are there performance benefits or prerequisite requirements (x64 native code, for example) that would require an x64 build?

Let's make the x86 prerequisite documentation an issue (so we can track progress) and put a Win x64 build out there as an issue too.

**Comment by RaiMan** [comment]
Some people during the last 2 years requested, that they want to have a real 64Bit version for Windows. I never asked the reason and never tested myself about performance.

Some people wanted to have it with reference to the 64Bit Java version, they had on their system. But together with a question I learned, that you can activate the 32Bit Java API even on a 64Bit Java without the need to install an extra JRE 6 32Bit.

In the Linux version we have the 64Bit version (since you have to add the prereq's yourself). On Mac (which I use mainly) it is rather easy and straight forward to build a 64Bit version (I have it on my machines based on my Sikuli fork).

So I think if we can tell people how to build a real 64Bit version without much effort and even give them a build script, some people out there would be happy.

I come back to my suggestion: let's document this starting with a page in the Wiki. Will you set it up or should I do it?

**Comment by RaiMan** [comment]
No longer supported

**Pull request closed without merging**
